# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: soil

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6
  region: us-west-2

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
  environment:
    RDS_HOST: db.host.com
    RDS_DBNAME: dbanme
    RDS_USERNAME: username
    RDS_PASSWORD: password

# you can add packaging information here
package:
  include:
#    - include-me.py
    - psycopg2/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  soil:
    handler: handler.soil
    tags:
      created: serverless.yml for soil service

    events:
      - http:
          path: api/metrics/soil
          method: get
          cors: true
      - http:
          path: api/metrics/soil
          method: post
          cors: true

#    environment:
#      RDS_HOST: db.host.com
#      RDS_DBNAME: dbanme
#      RDS_USERNAME: username
#      RDS_PASSWORD: password



# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
