# uses aws/codebuild/nodejs:8.11.0
#
version: 0.2

#
# this builds the S3 static content
phases:

  install:
    commands:
      - cd bot-ui && npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build s3://$WEB_BUCKET/ --delete --acl public-read

artifacts:
  files:
    - "**/*"
  base-directory: build
