service: signalbot-graphql
#plugins:
#    - serverless-webpack

#custom:
#    webpackIncludeModules: true

provider:
    name: aws
    runtime: nodejs4.3
    region: us-west-2
    stage: dev

functions:
    graphql:
        handler: handler.graphql
        events:
            - http:
                path: graphql
                method: post
                cors: true


